/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as DriverSetupRouteImport } from './routes/driver-setup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RidesRideIdRouteImport } from './routes/rides.$rideId'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as RidesRideIdTrackRouteImport } from './routes/rides.$rideId_.track'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverSetupRoute = DriverSetupRouteImport.update({
  id: '/driver-setup',
  path: '/driver-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdRoute = RidesRideIdRouteImport.update({
  id: '/rides/$rideId',
  path: '/rides/$rideId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RidesRideIdTrackRoute = RidesRideIdTrackRouteImport.update({
  id: '/rides/$rideId_/track',
  path: '/rides/$rideId/track',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver-setup': typeof DriverSetupRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/$rideId/track': typeof RidesRideIdTrackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver-setup': typeof DriverSetupRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/$rideId/track': typeof RidesRideIdTrackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/driver-setup': typeof DriverSetupRoute
  '/publish': typeof PublishRoute
  '/search': typeof SearchRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/rides/$rideId': typeof RidesRideIdRoute
  '/rides/$rideId_/track': typeof RidesRideIdTrackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/driver-setup'
    | '/publish'
    | '/search'
    | '/admin/dashboard'
    | '/admin/login'
    | '/rides/$rideId'
    | '/rides/$rideId/track'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/driver-setup'
    | '/publish'
    | '/search'
    | '/admin/dashboard'
    | '/admin/login'
    | '/rides/$rideId'
    | '/rides/$rideId/track'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/dashboard'
    | '/driver-setup'
    | '/publish'
    | '/search'
    | '/admin/dashboard'
    | '/admin/login'
    | '/rides/$rideId'
    | '/rides/$rideId_/track'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DriverSetupRoute: typeof DriverSetupRoute
  PublishRoute: typeof PublishRoute
  SearchRoute: typeof SearchRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  RidesRideIdRoute: typeof RidesRideIdRoute
  RidesRideIdTrackRoute: typeof RidesRideIdTrackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-setup': {
      id: '/driver-setup'
      path: '/driver-setup'
      fullPath: '/driver-setup'
      preLoaderRoute: typeof DriverSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$rideId': {
      id: '/rides/$rideId'
      path: '/rides/$rideId'
      fullPath: '/rides/$rideId'
      preLoaderRoute: typeof RidesRideIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rides/$rideId_/track': {
      id: '/rides/$rideId_/track'
      path: '/rides/$rideId/track'
      fullPath: '/rides/$rideId/track'
      preLoaderRoute: typeof RidesRideIdTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DriverSetupRoute: DriverSetupRoute,
  PublishRoute: PublishRoute,
  SearchRoute: SearchRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  RidesRideIdRoute: RidesRideIdRoute,
  RidesRideIdTrackRoute: RidesRideIdTrackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
